name: Continuous Integration

on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  build_jar:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Assemble JAR
        run: ./gradlew bootJar

      - name: Upload JAR file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-jar
          path: build/libs/*.jar

      - name: Set Version
        id: set_version
        run: echo "::set-output name=version::$(echo $GITHUB_RUN_NUMBER)"

  build_docker_file:
    needs: [ build_jar ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download JAR file as artifact
        uses: actions/download-artifact@v3
        with:
          name: built-jar
          path: build/libs

      - name: Build Docker Image
        run: |
          docker build -t mcoslet/utm_master_ac_lab:latest -t mcoslet/utm_master_ac_lab:${{needs.build_jar.outputs.version}} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push mcoslet/utm_master_ac_lab:${{ needs.build_jar.outputs.version }}
          docker push mcoslet/utm_master_ac_lab:latest
