# https://zeet.co/blog/kubernetes-deployment-history
# https://kubernetes.io/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_undo/
name: Rollback the EKS to stable version
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version you want to roll back to, example: "
        required: false
        default: ""
jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks --region us-east-1 update-kubeconfig --name mcoslet_ac_lab_master
      - name: Rollback
        run: |
          if ["${{github.event.inputs.version}}" == ""]; then
            kubectl rollout undo deployment/utm-spring-boot-mc-mm
          else
            kubectl rollout undo deployment/utm-spring-boot-mc-mm --to-revision=${{github.event.inputs.version}}